language: julia
os:
  - linux
#  - osx
julia:
#  - 0.4
  - nightly
notifications:
  email: false
script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("Log4jl"); Pkg.test("Log4jl"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Log4jl")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
